import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import dishes from '../src/data/dishes.json' with { type: 'json' }
import version from '../src/deploy-version.json' with { type: 'json' }
import { filterDishes } from '../src/dishLogic.mjs'
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
const checks = []
try {
  await page.goto('http://127.0.0.1:5173/')
  assert.ok((await page.locator('footer').textContent()).includes(`Version: Deploy ${version.deploy}`))
  await page.getByRole('button', { name: 'Chọn cho tôi' }).click()
  assert.equal(await page.locator('.result-section .grid .dish-card').count(), 12)
  const original = await page.locator('.result-section > .dish-card h3').textContent()
  await page.getByRole('button', { name: 'Đổi món' }).click()
  assert.notEqual(await page.locator('.result-section > .dish-card h3').textContent(), original)
  await page.getByRole('button', { name: 'Xem thêm', exact: true }).click()
  assert.equal(await page.locator('.result-section .grid .dish-card').count(), 24)
  checks.push('CASE 1: lunch list, next dish and load more')
  await page.locator('.control-card').getByRole('button', { name: 'Ăn vặt', exact: true }).click()
  await page.getByRole('button', { name: 'Chọn cho tôi' }).click()
  assert.equal(await page.locator('.result-section .grid .dish-card').count(), 12)
  assert.ok((await page.locator('.result-section .grid .dish-card .muted').allTextContents()).some(t => t.includes('Ăn vặt')))
  checks.push('CASE 2: snack list')
  await page.locator('.control-card').getByRole('button', { name: 'Tối', exact: true }).click()
  await page.getByLabel('Tăng số người').click(); await page.getByLabel('Tăng số người').click()
  await page.locator('#budget').selectOption('100000')
  await page.getByRole('button', { name: 'Mâm cơm', exact: true }).click()
  await page.getByRole('button', { name: 'Chọn cho tôi' }).click()
  assert.equal(await page.locator('.result-section .grid').first().locator('.dish-card').count(), 3)
  assert.ok((await page.getByRole('heading', { name: 'Mâm cơm cho 4 người' }).count()) === 1)
  const totalText = await page.locator('.result-section > p').allTextContents()
  assert.ok(totalText.some(t => t.includes('400.000đ')))
  checks.push('CASE 3: dinner tray for four')
  await page.getByRole('button', { name: 'Món ăn', exact: true }).click()
  assert.ok((await page.locator('.page .center.muted').textContent()).includes('1.000') || (await page.locator('.page .center.muted').textContent()).includes('1000'))
  for (const query of ['ga', 'GÀ', 'banh', 'cá']) {
    await page.getByRole('textbox', { name: 'Tìm tên món' }).fill(query)
    const expected = filterDishes(dishes, { search: query }).length
    assert.ok((await page.locator('.page .center.muted').textContent()).includes(`/ ${expected} món`))
    assert.equal(await page.locator('.page .dish-card').count(), Math.min(12, expected))
  }
  checks.push('CASE 4/5: accented, unaccented and case-insensitive search')
  await page.getByRole('textbox', { name: 'Tìm tên món' }).fill('')
  await page.locator('#catalog-meal').selectOption('Trưa')
  await page.locator('#catalog-type').selectOption('Xào')
  await page.locator('#catalog-budget').selectOption('80000')
  const expected = filterDishes(dishes, { meal: 'Trưa', type: 'Xào', budget: 80000 }).length
  assert.ok((await page.locator('.page .center.muted').textContent()).includes(`/ ${expected} món`))
  await page.locator('#catalog-meal').selectOption('Tất cả'); await page.locator('#catalog-type').selectOption('Tất cả'); await page.locator('#catalog-budget').selectOption('Infinity')
  await page.getByRole('textbox', { name: 'Tìm tên món' }).fill('Bánh tiêu')
  const image = page.locator('.dish-card img').first()
  await image.scrollIntoViewIfNeeded(); await page.waitForTimeout(300)
  assert.ok(await image.evaluate(img => img.complete && img.naturalWidth > 0))
  assert.ok((await image.getAttribute('src')).includes('/images/banh-tieu.jpg?v='))
  checks.push('CASE 6: Bánh tiêu loads its reviewed local photo with new cache version')
  await page.getByRole('textbox', { name: 'Tìm tên món' }).fill('')
  await page.locator('.heart').first().click()
  await page.getByRole('button', { name: 'Yêu thích', exact: true }).click()
  assert.equal(await page.locator('.page .dish-card').count(), 1)
  await page.reload(); await page.getByRole('button', { name: 'Yêu thích', exact: true }).click()
  assert.equal(await page.locator('.page .dish-card').count(), 1)
  checks.push('favorites persist after reload')
  await page.getByRole('button', { name: '7 ngày', exact: true }).click()
  await page.getByRole('button', { name: 'Tạo thực đơn' }).click()
  assert.equal(await page.locator('.day-card').count(), 7)
  await page.getByRole('button', { name: 'Đi chợ', exact: true }).click()
  assert.ok(await page.locator('.shopping-list input').count() > 0)
  await page.locator('.shopping-list input').first().check()
  await page.reload(); await page.getByRole('button', { name: 'Đi chợ', exact: true }).click()
  assert.equal(await page.locator('.shopping-list input').first().isChecked(), true)
  checks.push('latest GitHub weekly planner and shopping checklist retained and persisted')
  await page.getByRole('button', { name: 'Món ăn', exact: true }).click()
  for (const [name, width, columns] of [['desktop', 1440, 3], ['tablet', 768, 2], ['mobile', 390, 1], ['small-mobile', 320, 1]]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.waitForTimeout(150)
    const layout = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, columns: getComputedStyle(document.querySelector('.grid')).gridTemplateColumns.split(' ').length }))
    assert.equal(layout.overflow, false, `${name} overflows`)
    assert.equal(layout.columns, columns)
    await page.screenshot({ path: `reports/${name}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Hôm nay', exact: true }).click()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${name} home overflows`)
    await page.getByRole('button', { name: 'Món ăn', exact: true }).click()
    checks.push(`${name}: ${columns} columns, no horizontal overflow`)
  }
  assert.deepEqual(errors, [])
  const fallbackPage = await browser.newPage()
  let failedRequests = 0
  await fallbackPage.route('**/images/banh-tieu.jpg*', route => { failedRequests++; return route.abort() })
  await fallbackPage.goto('http://127.0.0.1:5173/')
  await fallbackPage.getByRole('button', { name: 'Món ăn', exact: true }).click()
  await fallbackPage.getByRole('textbox', { name: 'Tìm tên món' }).fill('Bánh tiêu')
  const fallback = fallbackPage.locator('.dish-card img')
  await fallback.scrollIntoViewIfNeeded()
  await fallbackPage.waitForFunction(() => document.querySelector('.dish-card img')?.src.startsWith('data:image/svg+xml'))
  assert.ok(failedRequests <= 2, 'fallback must not retry indefinitely')
  await fallbackPage.close()
  checks.push('broken primary image falls back to placeholder without a retry loop (forced failure test)')
  await fs.writeFile('reports/browser-check.json', JSON.stringify({ checks, consoleErrors: errors }, null, 2))
  console.log(JSON.stringify({ checks, consoleErrors: errors }, null, 2))
} finally { await browser.close() }
